/**
 * Es6 module for Redux Architecture.
 * This file just serves some constants for the config state.
 *
 * @file
 * @module
 *
 * @author hello@ulrichmerkel.com (Ulrich Merkel), 2016
 * @version 0.0.1
 *
 * @changelog
 * - 0.0.1 basic functions and structure
 */
export const FETCH_CONFIG_CONTENT_REQUEST = 'FETCH_CONFIG_CONTENT_REQUEST';
export const FETCH_CONFIG_CONTENT_FAILURE = 'FETCH_CONFIG_CONTENT_FAILURE';
export const FETCH_CONFIG_CONTENT_SUCCESS = 'FETCH_CONFIG_CONTENT_SUCCESS';
export const CONFIG_CONTENT_ADD = 'CONFIG_CONTENT_ADD';
export const CONFIG_CONTENT_INVALIDATE = 'CONFIG_CONTENT_INVALIDATE';

export const FETCH_CONFIG_TRANSLATION_REQUEST = 'FETCH_CONFIG_TRANSLATION_REQUEST';
export const FETCH_CONFIG_TRANSLATION_FAILURE = 'FETCH_CONFIG_TRANSLATION_FAILURE';
export const FETCH_CONFIG_TRANSLATION_SUCCESS = 'FETCH_CONFIG_TRANSLATION_SUCCESS';
export const CONFIG_TRANSLATION_ADD = 'CONFIG_TRANSLATION_ADD';
export const CONFIG_TRANSLATION_INVALIDATE = 'CONFIG_TRANSLATION_INVALIDATE';
