language: node_js
node_js:
  - "8.1.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
install:
  - "npm install -g yarn@1.0.2"
  - "yarn --pure-lockfile"
script: npm run travis
after_success: npm run coverage
branches:
  only:
    - master
    - develop
    - feature
    - /^greenkeeper/.*$/
sudo: false
