language: node_js
node_js:
  - "8.1.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
before_install:
  - npm install -g yarn@1.0.2
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn --pure-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script: npm run travis
after_success: npm run coverage
branches:
  only:
    - master
    - develop
    - feature
sudo: false
