language: node_js
node_js:
  - "8.1.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn --pure-lockfile
script: npm run travis
after_success: npm run coverage
branches:
  only:
    - master
    - develop
    - feature
sudo: false
cache:
  yarn: true
