language: node_js
node_js:
  - "6.5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
install:
  - "npm install -g yarn"
  - "yarn install && yarn install"
script: npm run travis
after_success: npm run coverage
branches:
  only:
    - master
    - develop
    - feature
sudo: false
